# Generated by Django 3.1.4 on 2020-12-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='count',
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn',
        ),
    ]
