# Generated by Django 3.1.4 on 2020-12-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201228_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='post',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
